config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/users/:address/nonce', to: 'users#nonce'

  get '/profile', to: 'users#profile', as: :profile
  get '/profile/edit', to: 'users#edit_profile', as: :edit_profile
  patch '/profile', to: 'users#update_profile'
  put '/profile', to: 'users#update_profile'
  get '/p/:username', to: 'users#public_profile', as: :public_profile

  post '/sessions', to: 'sessions#create'
  delete '/sessions', to: 'sessions#destroy', as: :destroy_user_session

  get '/wallet/nfts', to: 'wallet#nfts', as: :wallet_nfts
  get '/wallet/:username/nfts', to: 'wallet#public_nfts', as: :public_wallet

  get '/vault/nfts', to: 'vault#nfts', as: :vault_nfts
end

app/models/user.rb
# frozen_string_literal: true

# User model
class User < ApplicationRecord
  TWITTER_URL = 'https://twitter.com'
  DISCORD_USER_URL = 'https://discordapp.com/users'

  validates :eth_address, presence: true, uniqueness: true
  attribute :eth_nonce, :string, default: -> { SecureRandom.uuid }
  validates :eth_nonce, presence: true, uniqueness: true
  validates :username, presence: true, uniqueness: true, length: { maximum: 42 },
                       format: {
                         with: /\A[a-zA-Z0-9\-_]+\z/,
                         message: 'should contain only letters, numbers, hyphens and underscores'
                       }

  before_validation { default_username }
  before_save { downcase_eth_address }

  def twitter_url
    "#{TWITTER_URL}/#{twitter_username}"
  end

  def discord_url
    "#{DISCORD_USER_URL}/#{discord_username}"
  end

  private

  def downcase_eth_address
    eth_address&.downcase!
  end

  def default_username
    self.username = eth_address&.downcase if username.blank?
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# Manages interactions with the user model
class UsersController < ApplicationController
  before_action :authenticate_user, except: %i[nonce public_profile]
  before_action :set_profile_metadata, only: %i[profile edit_profile update_profile public_profile]

  # GET /profile
  def profile; end

  # GET /profile/public
  def public_profile
    @user = User.find_by(username: public_profile_params[:username], public_profile: true)
  end

  # GET /profile/edit
  def edit_profile; end

  # PATCH/PUT /profile
  def update_profile
    if current_user.update(profile_params)
      redirect_to profile_path
    else
      render :edit_profile, status: :unprocessable_entity
    end
  end

  # GET /users/:address/nonce
  def nonce
    params_address = Eth::Address.new user_params[:address]
    return unless params_address.valid?

    user = User.find_or_create_by!(eth_address: user_params[:address].downcase)
    render json: [eth_nonce: user.eth_nonce]
  end

  private

  def set_profile_metadata
    @screen_css_prefix = 'profile-'
    @page_title = if action_name == 'public_profile'
                    "#{public_profile_params[:username]} | Clementine's Nightmare Dashboard"
                  else
                    "Profile | Clementine's Nightmare Dashboard"
                  end
    @page_description = "User profile for Clementine's Nightmare Dashboard"
    @page_image_asset = ''
  end

  def user_params
    params.permit(:address)
  end

  def profile_params
    params.require(:user).permit(:username, :twitter_username, :discord_username, :public_profile)
  end

  def public_profile_params
    params.permit(:username)
  end
end

app/views/users/edit_profile.html.erb
<%= turbo_frame_tag :user_profile_show_and_edit do %>
  <%= form_with(model: current_user, url: profile_path) do |form| %>
    <div class="profile-fields">
      <fieldset>
        <p>
          <label for="username">Username</label>
          <%= form.text_field :username, maxlength: 64 %>
        </p>
        <p>
          <label for="twitter_username">Twitter Username</label>
          <%= form.text_field :twitter_username, maxlength: 15 %>
        </p>
        <p>
          <label for="discord_username">Discord Username</label>
          <%= form.text_field :discord_username, maxlength: 32 %>
        </p>
        <p>
          <label for="public_profile" class="checkbox">Create a Public Profile?<sup class="tooltip-asterisk">*</sup></label>
          <%= form.check_box :public_profile %>
        </p>
        <p>
          <%= form.submit 'Save', class: "button" %>
        </p>
        <p class="tooltip">
          <sup class="tooltip-asterisk">*</sup> A public profile allows you to showcase your Clementine's NFT collection to the world.
        </p>
      </fieldset>
    </div>
  <%- end -%>
  <%- if current_user.errors.any? -%>
    <div class="error-messages">
      <h2><%= pluralize(current_user.errors.count, 'error') %> prohibited your changes from being saved:</h2>
      <ul>
        <%- current_user.errors.each do |error| -%>
          <li><%= error.full_message %></li>
        <%- end -%>
      </ul>
    </div>
  <%- end -%>
<%- end -%>

app/views/users/profile.html.erb
<div class="profile-container">
  <%= turbo_frame_tag :user_profile_show_and_edit do %>
    <div class="profile-fields">
      <fieldset>
        <p>
          <label for="username">Username</label>
          <span class="force-wrap"><%= current_user.username %></span>
        </p>
        <!--
        <p>
          <label for="lunchmoney">Lunch Money</label>
          <%#= current_user.lunch_money %>
        </p>
        -->
        <% if current_user.twitter_username.present? %>
          <p>
            <label for="twitter_username">Twitter Username</label>
            <%= current_user.twitter_username.presence || 'N/A' %>
          </p>
        <% end %>
        <% if current_user.discord_username.present? %>
          <p>
            <label for="discord_username">Discord Username</label>
            <%= current_user.discord_username.presence || 'N/A' %>
          </p>
        <% end %>
        <p>
          <label for="public_profile">Public</label>
          <%= current_user.public_profile ? 'Yes' : 'No' %>
        </p>
        <p>
          <%= link_to 'Edit', edit_profile_path, class: 'button' %>
          <% if current_user.public_profile %>
            <%= link_to 'View Profile', public_profile_path(current_user.username), class: 'button' %>
          <% end %>
        </p>
      </fieldset>
    </div>
  <% end %>
</div>

app/views/users/public_profile.html.erb
<div class="public-profile-container">
  <% if @user && @user.public_profile %>
    <section class="username">
      <h1><%= @user.username %></h1>
    </section>
    <% if @user.twitter_username.present? || @user.discord_username.present? %>
      <section class="user-socials">
        <div class="social">
          <a href="<%= @user.twitter_url %>" target="_blank" class="social-link">
            <img src="<%= asset_path('twitter-white.png')%>" class="social-icon">
          </a>
        </div>
        <div class="social">
          <a href="<%= @user.discord_url %>" target="_blank" class="social-link">
            <img src="<%= asset_path('discord-white.png')%>" class="social-icon">
          </a>
        </div>
      </section>
    <% end %>
    <div id="public-wallet-container">
      <%= turbo_frame_tag "public-wallet", src: public_wallet_path(@user.username) do %>
      <% end %>
    </div>
  <% else %>
    <p>Not Found</p>
  <% end %>
</div>