config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/users/:address/nonce', to: 'users#nonce'

  get '/profile', to: 'users#profile', as: :profile
  get '/profile/edit', to: 'users#edit_profile', as: :edit_profile
  patch '/profile', to: 'users#update_profile'
  put '/profile', to: 'users#update_profile'
  get '/p/:username', to: 'users#public_profile', as: :public_profile

  post '/sessions', to: 'sessions#create'
  delete '/sessions', to: 'sessions#destroy', as: :destroy_user_session

  get '/wallet/nfts', to: 'wallet#nfts', as: :wallet_nfts
  get '/wallet/:username/nfts', to: 'wallet#public_nfts', as: :public_wallet

  get '/vault/nfts', to: 'vault#nfts', as: :vault_nfts
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# Home page controller
class HomeController < ApplicationController
  # GET /
  def index
    @screen_css_prefix = 'home-'
    @page_title = "Clementine's Nightmare Dashboard"
    @page_description = "Dashboard for Clementine's Nightmare!"
    @page_image_asset = ''
    @load_eth_js = !logged_in?
  end
end

app/views/home/_logged_in.html.erb
<div class="logged-in-container">
  <div class="wallet-vault-buttons">
    <button id="wallet-button" class="button wallet"/>
    <button id="vault-button" class="button vault"/>
  </div>
  <div class="welcome-message">Welcome to the Neighborhood <span class="force-wrap"><%= current_user.username %></span>!</div>
  <div>
    <div id="wallet-container">
      <%= turbo_frame_tag "wallet", src: wallet_nfts_path do %>
      <% end %>
    </div>
    <div id="vault-container" class="hidden">
      <%= turbo_frame_tag "vault", src: vault_nfts_path do %>
      <% end %>
    </div>
  </div>
</div>

<script>
    function show_wallet() {
        let wallet = document.getElementById('wallet-container')
        let vault = document.getElementById('vault-container')

        if (!vault.classList.contains('hidden')) {
            vault.classList.add('hidden')
        }

        if (wallet.classList.contains('hidden')) {
            wallet.classList.remove('hidden')
        }
    }

    function show_vault() {
        let wallet = document.getElementById('wallet-container')
        let vault = document.getElementById('vault-container')

        if (!wallet.classList.contains('hidden')) {
            wallet.classList.add('hidden')
        }

        if (vault.classList.contains('hidden')) {
            vault.classList.remove('hidden')
        }
    }


    document.getElementById('wallet-button').onclick = show_wallet
    document.getElementById('vault-button').onclick = show_vault

    //# sourceURL=logged-in-home.js
</script>

app/views/home/_logged_out.html.erb
<div class="logged-out-container">
  <div class="logged-out-section">
    <a href="https://clementinesnightmare.com">
      <img src="<%= asset_path('logo.png') %>" alt="Clementine's Nightmare Logo" class="logo"/>
    </a>
  </div>
  <div class="logged-out-section">
    Connect to Ethereum.
  </div>
  <div class="logged-out-section">
    <button class="button login" />
  </div>
</div>
<%= render partial: 'sessions/new' %>

app/views/home/index.html.erb
<%- if logged_in? -%>
  <%= render partial: 'home/logged_in' %>
<%- else -%>
  <%= render partial: 'home/logged_out' %>
<%- end -%>